# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: a10s.ca
email: bonjour@a10s.ca
description: >- # this means to ignore newlines until "baseurl:"
  Culture | Numérique | Collaboration
baseurl: "" # the subpath of your site, e.g. /blog
slogan: Culture | Numérique | Collaboration
url: "https://a10s.ca" # the base hostname & protocol for your site, e.g. http://example.com or  https://tradejk.netlify.com
twitter_url: "https://twitter.com/a10s_ca"
github_url:  "https://github.com/a10s-ca/"
logo: "/assets/images/logo_head.png"
logo_2: "/assets/images/logo_foot.png"

permalink: "/:title"

copyright_text: "Copyright © 2021. Tous droits réservés."
cover_image: "/assets/images/page-title-bg.jpg"

sass:
    sass_dir: _sass

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
